### ISSUE TITLE
add user's locale to fedora-toolbox user image

### ISSUE THREAD

**Issue by juhp** [debarshiray/toolbox#71] opened 2019-03-04 03:38 UTC
I think fedora containers only include glibc-langpack-en by default.
So to handle this better I suggest either fallback to en_US.utf8 or C.utf8, but I don't know how to do that, so better would be to add the glibc-langpack-xx package for the user's locale to the user fedora-toolbox image.

**Comment by debarshiray** [comment] 2019-03-05 17:05
Duplicate of #60

**Closed** 2019-03-05 17:25 UTC
