### ISSUE TITLE
toolbox: failed to create working container

### ISSUE THREAD

**Issue by koenigjaeger** [debarshiray/toolbox#87] opened 2019-03-22 19:55 UTC
**Issue:**
Toolbox is not able to create a container on Fedora Silverblue 29 using version 0.0.6 of toolbox (whats currently in fedora repos).

CPU: Intel® Core™ i7 CPU 860 @ 2.80GHz × 8 
GPU: AMD® Verde

All opensource drivers.

**Error:**
```
$ toolbox -v create
toolbox: checking if image fedora-toolbox-$USER:29 already exists
ERRO[0000] 'overlay' is not supported over extfs at "/var/home/$USER/.local/share/containers/storage/overlay" 
ERRO[0000] [graphdriver] prior storage driver overlay failed: kernel does not support overlay fs: 'overlay' is not supported over extfs at "/var/home/$USER/.local/share/containers/storage/overlay": backing file system is unsupported for this graph driver 
ERRO[0000] exit status 1                                
toolbox: trying to create working container toolbox-working-container-33267118-4cdb-11e9-b5ed-001018000000
toolbox: looking for image localhost/fedora-toolbox:29
ERRO[0000] 'overlay' is not supported over extfs at "/var/home/$USER/.local/share/containers/storage/overlay" 
ERRO[0000] [graphdriver] prior storage driver overlay failed: kernel does not support overlay fs: 'overlay' is not supported over extfs at "/var/home/$USER/.local/share/containers/storage/overlay": backing file system is unsupported for this graph driver 
ERRO[0000] exit status 1                                
toolbox: looking for image registry.fedoraproject.org/f29/fedora-toolbox:29
ERRO[0000] 'overlay' is not supported over extfs at "/var/home/$USER/.local/share/containers/storage/overlay" 
ERRO[0000] [graphdriver] prior storage driver overlay failed: kernel does not support overlay fs: 'overlay' is not supported over extfs at "/var/home/$USER/.local/share/containers/storage/overlay": backing file system is unsupported for this graph driver 
```

**Comment by debarshiray** [comment] 2019-03-27 14:38
Duplicate of #42

**Comment by debarshiray** [comment] 2019-03-27 14:38
This is due to one underlying Podman bug or another.

Verify that `~/.config/containers/storage.conf` is not using a camel-case format. If it is, then replace it with the lower-case example in https://github.com/containers/libpod/issues/2158. Then `sudo rm -rf ~/.local/share/containers` and try again. However, you'd lose all existing containers and images.

**Closed by debarshiray** 2019-03-27 14:38 UTC
