### ISSUE TITLE
Rendering issue in tmux

### ISSUE THREAD

**Issue by Frederik-Baetens** [debarshiray/toolbox#154] opened 2019-05-11 21:53 UTC
Steps to reproduce:
- Open tmux in a toolbox container,
- type ls a few times
- type clear
Expected: console should be cleared
Actual: it isn't cleared but glitched instead.

This was tried both on silverblue 30 and fedora workstation 30

See screenshot of the issue: https://imgur.com/a/qyi2ap4
(a seperate bug can also be seen where i try to install software that's not in the container, but it says that it is installed already, presumably because it's installed on the host os)

My issue is different from #60 because i don't get the error output from locale, and i also have tried the solutions posted there.

I also sometimes get `error connecting to /tmp/tmux-1000/default (No such device or address)`
when trying to open tmux in a container, but i don't know what triggers that exactly (still works fine in a fresh container and on the host)

**Comment by debarshiray** [comment] 2019-05-23 18:02
Duplicate of #14

**Closed by debarshiray** 2019-05-23 18:02 UTC
