### ISSUE TITLE
Error starting toolbox runc and Cgroups v2

### ISSUE THREAD

**Issue by garrett** [debarshiray/toolbox#246] opened 2019-09-03 08:55 UTC
I cannot run any toolbox containers in Fedora 31 (alpha) Silveblue.

I'm not sure if this is a problem with toolbox, podman, a mismatch between the toolbox & podman, a system configuration issue in Fedora, or something Silverblue specific.

## Versions

- Fedora Silverblue 31.20190902.n.0 (2019-09-02T08:29:58Z)
- toolbox-0.0.12-2.fc31.noarch
- podman-1.5.1-2.16.dev.gitce64c14.fc31.x86_64

## Existing container

```
$ toolbox -v enter --container fedora-toolbox-30

toolbox: resolved absolute path for /usr/bin/toolbox to /usr/bin/toolbox
toolbox: checking if /etc/subgid and /etc/subuid have entries for user garrett
toolbox: TOOLBOX_PATH is /usr/bin/toolbox
toolbox: checking if 'podman system migrate' exists
toolbox: migration not needed: 1.5.1-dev is unchanged
toolbox: Fedora generational core is f31
toolbox: base image is fedora-toolbox:31
toolbox: container is fedora-toolbox-30
toolbox: checking if container fedora-toolbox-30 exists
toolbox: calling org.freedesktop.Flatpak.SessionHelper.RequestSession
toolbox: starting container fedora-toolbox-30
toolbox: /etc/profile.d/toolbox.sh already mounted in container fedora-toolbox-30
Error: unable to start container "fedora-toolbox-30": error reading container (probably exited) json message: EOF
toolbox: failed to start container fedora-toolbox-30
```

## New container

```
$ toolbox create -c test2 -r 31

Created container: test2
Enter with: toolbox enter --container test2

$ toolbox -v enter --container test2

toolbox: resolved absolute path for /usr/bin/toolbox to /usr/bin/toolbox
toolbox: checking if /etc/subgid and /etc/subuid have entries for user garrett
toolbox: TOOLBOX_PATH is /usr/bin/toolbox
toolbox: checking if 'podman system migrate' exists
toolbox: migration not needed: 1.5.1-dev is unchanged
toolbox: Fedora generational core is f31
toolbox: base image is fedora-toolbox:31
toolbox: container is test2
toolbox: checking if container test2 exists
toolbox: calling org.freedesktop.Flatpak.SessionHelper.RequestSession
toolbox: starting container test2
toolbox: /etc/profile.d/toolbox.sh already mounted in container test2
Error: unable to start container "test2": time="2019-09-03T10:47:15+02:00" level=warning msg="signal: killed"
time="2019-09-03T10:47:15+02:00" level=warning msg="no such directory for freezer.state"
time="2019-09-03T10:47:15+02:00" level=warning msg="no such directory for freezer.state"
time="2019-09-03T10:47:15+02:00" level=error msg="container_linux.go:346: starting container process caused \"process_linux.go:297: applying cgroup configuration for process caused \\\"mountpoint for cgroup not found\\\"\"\n"
container_linux.go:346: starting container process caused "process_linux.go:297: applying cgroup configuration for process caused \"mountpoint for cgroup not found\"": OCI runtime error
toolbox: failed to start container test2
```

**Comment by HarryPhoon** [comment] 2019-09-03 09:10
I would say that the problem is caused by Podman. I'm not sure exactly what it is but I'll try to look at it.

**Comment by debarshiray** [comment] 2019-09-03 19:29
This is likely due to the [introduction of CGroups v2](https://fedoraproject.org/wiki/Changes/CGroupsV2) in Fedora 31.

**Comment by debarshiray** [comment] 2019-09-10 11:04
@garrett was this a clean new Fedora 31 Silverblue install? Or did you upgrade?

I am asking because it might be due to configuration file issues in `/etc`.

**Comment by debarshiray** [comment] 2019-09-10 11:12
> ## Versions
> 
>     * Fedora Silverblue 31.20190902.n.0 (2019-09-02T08:29:58Z)
> 
>     * toolbox-0.0.12-2.fc31.noarch
> 
>     * podman-1.5.1-2.16.dev.gitce64c14.fc31.x86_64

`podman-1.5.1-2.16.dev.gitce64c14.fc31` was still using `runc` as the OCI container runtime, and it doesn't work with Cgroups v2 which is what Fedora 31 uses.

`podman-1.5.1-2.17.dev.gitce64c14.fc31` is the build that switched to a different runtime, `crun`. Using that build would at least get you a bit further.

Let's close this. Please do open a new issue if the new build leads to another failure.

**Closed by debarshiray** 2019-09-10 11:12 UTC

**Comment by returntrip** [comment] 2019-09-13 15:42
Filed issue with libpod: https://github.com/containers/libpod/issues/4024

**Comment by debarshiray** [comment] 2019-09-13 15:42
@garrett does this represent your issue: https://github.com/containers/libpod/issues/4024 ?

**Comment by garrett** [comment] 2019-09-15 20:18
@debarshiray: I did! Yeah, it probably should be another error. I'll try again tomorrow with the latest Silverblue Fedora 31 beta.

Thanks for your effort on this! (I know it has been more of a podman issue, so extra thanks!)

**Comment by debarshiray** [comment] 2019-09-16 11:42
> Thanks for your effort on this!

My pleasure. :)
