### ISSUE TITLE
Cannot enter toolbox after reboot

### ISSUE THREAD

**Issue by andmalc** [debarshiray/toolbox#69] opened 2019-03-01 19:28 UTC
Toolbox under non-root was working before rebooting to update Silverblue to current version 29.20190219.0.  Now toolbox-enter fails with the following error.  It's necessary to remove the toolbox container and then allow toolbox-enter to recreate it.

```
fedora-toolbox -v enter 
/usr/bin/fedora-toolbox: trying to start container fedora-toolbox-andmalc:29
unable to start container "fedora-toolbox-andmalc:29": unable to find user andmalc: no matching entries in passwd file
/usr/bin/fedora-toolbox: failed to start container fedora-toolbox-andmalc:29
```
The container does exist:
```
podman ps --all
CONTAINER ID  IMAGE                                   COMMAND               CREATED     STATUS   PORTS  NAMES
ced84272c801  localhost/fedora-toolbox-andmalc:29     /bin/sh               5 days ago  Created         fedora-toolbox-andmalc:29```
```
```
podman --version
podman version 1.0.0

buildah --version
buildah version 1.7 (image-spec 1.0.0, runtime-spec 1.0.0)

rpm-ostree status
State: idle
AutomaticUpdates: disabled
Deployments:
● ostree://fedora-atomic-29:fedora/29/x86_64/atomic-host
                   Version: 29.20190219.0 (2019-02-19T04:52:26Z)
                BaseCommit: d00adf110907f93f6cdd05deda0e2878c9bd71c74e0c4c2e9a5250d2f4cc8868
              GPGSignature: Valid signature by 5A03B4DD8254ECA02FDA1637A20AA56B429476B4
           LayeredPackages: fedora-toolbox git

  ostree://fedora-atomic-29:fedora/29/x86_64/atomic-host
                   Version: 29.20190219.0 (2019-02-19T04:52:26Z)
                BaseCommit: d00adf110907f93f6cdd05deda0e2878c9bd71c74e0c4c2e9a5250d2f4cc8868
              GPGSignature: Valid signature by 5A03B4DD8254ECA02FDA1637A20AA56B429476B4
           LayeredPackages: fedora-toolbox git
```

**Comment by tosmi** [comment] 2019-03-05 17:22
could this be related to #62? i would try to run the latest toolbox from git.

hth
toni

**Comment by debarshiray** [comment] 2019-03-05 17:24
Indeed, it does look like a duplicate. Although, I am suprised how you got affected on Fedora 29 because my understanding was that the Podman regression was limited to Git snapshots shipped only on Fedoras 30 and 31.

**Comment by debarshiray** [comment] 2019-03-05 17:25
Duplicate of #62

**Closed** 2019-03-05 17:25 UTC
