### ISSUE TITLE
toolbox version. 

### ISSUE THREAD

**Issue by thawkins** [debarshiray/toolbox#222] opened 2019-07-15 02:49 UTC
Please add a

$toolbox version

command handler, to display the version information for toolbox 

Both podman and buildah have this. 

podman:
[tim.hawkins@localhost ~]$ podman version
Version:            1.4.5-dev
RemoteAPI Version:  1
Go Version:         go1.12.6
OS/Arch:            linux/amd64
[tim.hawkins@localhost ~]$ 

buildah:
[tim.hawkins@localhost ~]$ buildah version
Version:         1.9.0
Go Version:      go1.12.5
Image Spec:      1.0.0
Runtime Spec:    1.0.0
CNI Spec:        0.4.0
libcni Version:  
Git Commit:      
Built:           Thu Jan  1 08:00:00 1970
OS/Arch:         linux/amd64
[tim.hawkins@localhost ~]$ 

It makes the process of reporting issues easier to document.

**Comment by HarryPhoon** [comment] 2019-07-15 11:32
Hey, @thawkins, thanks for the heads up. What kind of info is needed to show?? I was thinking of:. toolbox version, podman version and possibly OS + Arch. I guess that could be enough.

**Comment by thawkins** [comment] 2019-07-15 11:39
Anything that would be required to report bugs, i think the list you gave is a good start.

**Comment by debarshiray** [comment] 2019-07-22 17:50
Duplicate of https://github.com/debarshiray/toolbox/issues/49

**Closed** 2019-07-22 17:51 UTC
