### ISSUE TITLE
sudo: /usr/bin/sudo must be owned by uid 0 and have the setuid bit set

### ISSUE THREAD

**Issue by barnscott** [debarshiray/toolbox#180] opened 2019-05-29 01:48 UTC
I get the following error when trying to use any sudo command. Issue began very recently, didnt have any issues in past. I went far enough to rm my toolbox container and rmi the image, but same issue persist on new toolbox container.

> sudo: /usr/bin/sudo must be owned by uid 0 and have the setuid bit set

Using Fedora Silverblue 30:
$ rpm -qa toolbox
toolbox-0.0.9-1.fc30.noarch
$ buildah --version
buildah version 1.8.2 (image-spec 1.0.0, runtime-spec 1.0.0)
$ podman --version
podman version 1.3.1

**Comment by debarshiray** [comment] 2019-05-29 22:26
There used to be a [bug](https://github.com/containers/libpod/issues/1526) like this but it was fixed long ago. So, this must be something else.

Two things. Don't use `podman-1.3.1`. Instead revert back to `podman-1.2.0`. Second, try `toolbox-0.0.10` because it doesn't use Buildah anymore. So one less variable to worry about.

**Comment by msheiny** [comment] 2019-05-29 22:40
> Two things. Don't use podman-1.3.1. Instead revert back to podman-1.2.0. Second, try toolbox-0.0.10 because it doesn't use Buildah anymore. So one less variable to worry about.

Hey @debarshiray - I fully realize you have a lot of Fedora Silverblue users coming in here and pulling issues totally unrelated to this project (and more-so with podman or Silverblue itself) and 10000% :heart: appreciate the work you do here. I have to add that I am also experiencing this issue, I tried using toolbox `0.0.10` to work around this to no avail. 

Regarding rolling back to an earlier podman version ... how do I even do that on silverblue? What implications does that have for the rest of the system? Once again I realize this problem is kinda out of your hands but I'm just pointing out this might be problematic advice for a subset of users.

**Comment by debarshiray** [comment] 2019-05-30 14:20
> Hey @debarshiray - I fully realize you have a lot of Fedora Silverblue users
> coming in here and pulling issues totally unrelated to this project (and more-so
> with podman or Silverblue itself) and 10000% heart appreciate the work you do
> here.

Thanks for the kind words. :)

> I have to add that I am also experiencing this issue, I tried using toolbox
> `0.0.10` to work around this to no avail.

I see, ok.

> Regarding rolling back to an earlier podman version ... how do I even do that on
> silverblue? What implications does that have for the rest of the system? Once
> again I realize this problem is kinda out of your hands but I'm just pointing out this
> might be problematic advice for a subset of users.

Try something like this:
```
$ rpm-ostree override remove podman-manpages
$ rpm-ostree override replace podman-1.2.0-2.git3bd528e.fc30.x86_64.rpm
```

You can then reboot into to the new image.

**Comment by debarshiray** [comment] 2019-06-11 11:06
Looks like this was another one of the regressions in Podman 1.3.1. Works for me with 1.4.0. Closing.

**Closed by debarshiray** 2019-06-11 11:06 UTC
