### ISSUE TITLE
cant run dnf inside toolbox

### ISSUE THREAD

**Issue by thawkins** [debarshiray/toolbox#191] opened 2019-06-10 08:45 UTC
I have finally got toolbox working on my FC30-workstation system, and i thought i would put it through its paces. 

however: 

having entered the toolbox:

```
> $[tim.hawkins@toolbox storage]$ sudo dnf install tcpdump
> sudo: /usr/bin/sudo must be owned by uid 0 and have the setuid bit set
> [tim.hawkins@toolbox storage]$ dnf install tcpdump
> Error: This command has to be run under the root user.
> [tim.hawkins@toolbox storage]$ whoami
> tim.hawkins
```

Im sure its just me being stupid, but this seems to indicate i cant use dnf inside a toolbox. which i thought was the whole point.

**Comment by changwuf31** [comment] 2019-06-11 09:12
see this issue: https://github.com/debarshiray/toolbox/issues/180

**Comment by debarshiray** [comment] 2019-06-11 10:52
Duplicate of #180

**Comment by debarshiray** [comment] 2019-06-11 10:53
Thanks for triaging this, @changwuf31

**Closed** 2019-07-22 14:33 UTC
