### ISSUE TITLE
dnf install/update fails

### ISSUE THREAD

**Issue by lumi-sch** [debarshiray/toolbox#155] opened 2019-05-12 12:02 UTC
Many package installs don't work.
Running on toolbox Fedora 30, with zsh as user shell (but bash as root shell).
The permissions of /bin/sh seem fine to me (`lrwxrwxrwx. 1 root root 4 Feb 16 10:03 /bin/sh -> bash`), so I'm not sure why that's happening.
```
➜  sudo dnf update
Last metadata expiration check: 0:02:36 ago on Sun 12 May 2019 11:50:56 AM UTC.
Dependencies resolved.
========================================================================================================================
 Package                          Architecture            Version                        Repository                Size
========================================================================================================================
Upgrading:
 glib-networking                  x86_64                  2.60.2-1.fc30                  updates                  140 k
 glib2                            x86_64                  2.60.2-1.fc30                  updates                  2.5 M
 subversion                       x86_64                  1.12.0-1.fc30                  updates                  1.1 M
 subversion-libs                  x86_64                  1.12.0-1.fc30                  updates                  1.5 M
 vte-profile                      x86_64                  0.56.3-1.fc30                  updates                   11 k

Transaction Summary
========================================================================================================================
Upgrade  5 Packages

Total download size: 5.3 M
Is this ok [y/N]: y
Downloading Packages:
(1/5): glib-networking-2.60.2-1.fc30.x86_64.rpm                                         444 kB/s | 140 kB     00:00    
(2/5): subversion-1.12.0-1.fc30.x86_64.rpm                                              558 kB/s | 1.1 MB     00:02    
(3/5): subversion-libs-1.12.0-1.fc30.x86_64.rpm                                         885 kB/s | 1.5 MB     00:01    
(4/5): vte-profile-0.56.3-1.fc30.x86_64.rpm                                             170 kB/s |  11 kB     00:00    
(5/5): glib2-2.60.2-1.fc30.x86_64.rpm                                                   895 kB/s | 2.5 MB     00:02    
------------------------------------------------------------------------------------------------------------------------
Total                                                                                   1.4 MB/s | 5.3 MB     00:03     
Running transaction check
Transaction check succeeded.
Running transaction test
Transaction test succeeded.
Running transaction
  Preparing        :                                                                                                1/1 
  Running scriptlet: subversion-libs-1.12.0-1.fc30.x86_64                                                           1/1 
error: failed to exec scriptlet interpreter /bin/sh: Permission denied
warning: %triggerun(systemd-241-8.git9ef65cb.fc30.x86_64) scriptlet failed, exit status 127

Error in <unknown> scriptlet in rpm package subversion-libs
  Upgrading        : subversion-libs-1.12.0-1.fc30.x86_64                                                          1/10 
  Upgrading        : glib2-2.60.2-1.fc30.x86_64                                                                    2/10 
  Upgrading        : glib-networking-2.60.2-1.fc30.x86_64                                                          3/10 
  Upgrading        : subversion-1.12.0-1.fc30.x86_64                                                               4/10 
  Running scriptlet: subversion-1.12.0-1.fc30.x86_64                                                               4/10 
error: failed to exec scriptlet interpreter /bin/sh: Permission denied
warning: %post(subversion-1.12.0-1.fc30.x86_64) scriptlet failed, exit status 127

Error in POSTIN scriptlet in rpm package subversion
  Upgrading        : vte-profile-0.56.3-1.fc30.x86_64                                                              5/10 
  Running scriptlet: subversion-1.11.1-4.fc30.x86_64                                                               6/10 
error: failed to exec scriptlet interpreter /bin/sh: Permission denied
error: %preun(subversion-1.11.1-4.fc30.x86_64) scriptlet failed, exit status 127

Error in PREUN scriptlet in rpm package subversion
  Cleanup          : glib-networking-2.60.1-2.fc30.x86_64                                                          7/10 
error: subversion-1.11.1-4.fc30.x86_64: erase failed

  Cleanup          : vte-profile-0.56.1-1.fc30.x86_64                                                              8/10 
  Cleanup          : glib2-2.60.1-2.fc30.x86_64                                                                    9/10 
  Cleanup          : subversion-libs-1.11.1-4.fc30.x86_64                                                         10/10 
  Running scriptlet: subversion-libs-1.11.1-4.fc30.x86_64                                                         10/10 
error: failed to exec scriptlet interpreter /bin/sh: Permission denied
warning: %triggerin(glibc-common-2.29-12.fc30.x86_64) scriptlet failed, exit status 127

Error in <unknown> scriptlet in rpm package subversion-libs
error: failed to exec scriptlet interpreter /bin/sh: Permission denied
warning: %triggerin(man-db-2.8.4-4.fc30.x86_64) scriptlet failed, exit status 127

Error in <unknown> scriptlet in rpm package subversion-libs
error: failed to exec scriptlet interpreter /bin/sh: Permission denied
warning: %triggerin(systemd-241-8.git9ef65cb.fc30.x86_64) scriptlet failed, exit status 127

Error in <unknown> scriptlet in rpm package subversion-libs
error: failed to exec scriptlet interpreter /bin/sh: Permission denied
warning: %triggerin(systemd-241-8.git9ef65cb.fc30.x86_64) scriptlet failed, exit status 127

Error in <unknown> scriptlet in rpm package subversion-libs
error: failed to exec scriptlet interpreter /bin/sh: Permission denied
warning: %triggerpostun(glibc-common-2.29-12.fc30.x86_64) scriptlet failed, exit status 127

Error in <unknown> scriptlet in rpm package subversion-libs
error: failed to exec scriptlet interpreter /bin/sh: Permission denied
warning: %triggerpostun(glib2-2.60.2-1.fc30.x86_64) scriptlet failed, exit status 127

Error in <unknown> scriptlet in rpm package subversion-libs
error: failed to exec scriptlet interpreter /bin/sh: Permission denied
warning: %triggerpostun(glib2-2.60.2-1.fc30.x86_64) scriptlet failed, exit status 127

Error in <unknown> scriptlet in rpm package subversion-libs
  Running scriptlet: glib2-2.60.2-1.fc30.x86_64                                                                   10/10 
error: failed to exec scriptlet interpreter /bin/sh: Permission denied
warning: %triggerin(glib2-2.60.2-1.fc30.x86_64) scriptlet failed, exit status 127

Error in <unknown> scriptlet in rpm package glib2
error: failed to exec scriptlet interpreter /bin/sh: Permission denied
warning: %triggerin(glib2-2.60.2-1.fc30.x86_64) scriptlet failed, exit status 127

Error in <unknown> scriptlet in rpm package glib2
  Verifying        : glib-networking-2.60.2-1.fc30.x86_64                                                          1/10 
  Verifying        : glib-networking-2.60.1-2.fc30.x86_64                                                          2/10 
  Verifying        : glib2-2.60.2-1.fc30.x86_64                                                                    3/10 
  Verifying        : glib2-2.60.1-2.fc30.x86_64                                                                    4/10 
  Verifying        : subversion-1.12.0-1.fc30.x86_64                                                               5/10 
  Verifying        : subversion-1.11.1-4.fc30.x86_64                                                               6/10 
  Verifying        : subversion-libs-1.12.0-1.fc30.x86_64                                                          7/10 
  Verifying        : subversion-libs-1.11.1-4.fc30.x86_64                                                          8/10 
  Verifying        : vte-profile-0.56.3-1.fc30.x86_64                                                              9/10 
  Verifying        : vte-profile-0.56.1-1.fc30.x86_64                                                             10/10 

Upgraded:
  glib-networking-2.60.2-1.fc30.x86_64      glib2-2.60.2-1.fc30.x86_64            subversion-1.12.0-1.fc30.x86_64     
  subversion-libs-1.12.0-1.fc30.x86_64      vte-profile-0.56.3-1.fc30.x86_64     

Failed:
  subversion-1.11.1-4.fc30.x86_64                                                                                       

Error: Transaction failed
```

**Comment by debarshiray** [comment] 2019-05-23 17:50
I tried installing and uninstalling `subversion-libs` on both Silverblue and legacy Workstation but can't reproduce this with a `/bin/bash` as the shell. Just to be sure, what does your `/etc/passwd` look like inside the toolbox container?

**Comment by debarshiray** [comment] 2019-05-23 18:01
Couldn't reproduce with a user and a container using zsh either. :/

**Comment by lumi-sch** [comment] 2019-05-23 18:17
> what does your `/etc/passwd` look like inside the toolbox container?

```
root:x:0:0:root:/root:/bin/bash
bin:x:1:1:bin:/bin:/sbin/nologin
daemon:x:2:2:daemon:/sbin:/sbin/nologin
adm:x:3:4:adm:/var/adm:/sbin/nologin
lp:x:4:7:lp:/var/spool/lpd:/sbin/nologin
sync:x:5:0:sync:/sbin:/bin/sync
shutdown:x:6:0:shutdown:/sbin:/sbin/shutdown
halt:x:7:0:halt:/sbin:/sbin/halt
mail:x:8:12:mail:/var/spool/mail:/sbin/nologin
operator:x:11:0:operator:/root:/sbin/nologin
games:x:12:100:games:/usr/games:/sbin/nologin
ftp:x:14:50:FTP User:/var/ftp:/sbin/nologin
nobody:x:65534:65534:Kernel Overflow User:/:/sbin/nologin
systemd-coredump:x:999:997:systemd Core Dumper:/:/sbin/nologin
systemd-network:x:192:192:systemd Network Management:/:/sbin/nologin
systemd-resolve:x:193:193:systemd Resolver:/:/sbin/nologin
dbus:x:81:81:System message bus:/:/sbin/nologin
unbound:x:998:996:Unbound DNS resolver:/etc/unbound:/sbin/nologin
systemd-timesync:x:995:995:systemd Time Synchronization:/:/sbin/nologin
tcpdump:x:72:72::/:/sbin/nologin
lumi:x:1000:1000::/home/lumi:/bin/zsh
```

**Comment by debarshiray** [comment] 2019-05-24 11:48
That seems ok. What were your `dnf` and `rpm` versions? I wonder if this was some bug in Fedora 30 that got fixed afterwards.

**Comment by cgwalters** [comment] 2019-05-24 13:08
https://github.com/cgwalters/coretoolbox/blob/3baa95ff48408fe8f42ddf576148250146f7f800/src/coretoolbox.rs#L358

**Comment by debarshiray** [comment] 2019-05-24 14:21
> https://github.com/cgwalters/coretoolbox/blob/3baa95ff48408fe8f42ddf576148250146f7f800/src/coretoolbox.rs#L358

That was reported some time ago (#47) and was fixed in Podman (https://github.com/containers/libpod/pull/2613). Is this really the same bug?

**Comment by lumi-sch** [comment] 2019-05-24 14:34
> What were your `dnf` and `rpm` versions?

```
$ rpm --version
RPM version 4.14.2.1
$ dnf --version
4.2.5
  Installed: dnf-0:4.2.5-1.fc30.noarch at Sat 11 May 2019 08:12:18 PM GMT
  Built    : Fedora Project at Tue 07 May 2019 03:11:38 PM GMT

  Installed: rpm-0:4.14.2.1-4.fc30.1.x86_64 at Wed 08 May 2019 08:08:24 AM GMT
  Built    : Fedora Project at Sat 02 Feb 2019 06:46:11 PM GMT

```

**Comment by cgwalters** [comment] 2019-05-24 14:35
Oh hum, now that I look at that code it's not running if you are using a pid namespace (as coretoolbox is).

Regardless though...things get messy here if `--privileged` is specified; I think the onus is on toolbox to mask out things not desired (like selinux) rather than podman doing it.

**Comment by mildred** [comment] 2019-07-17 08:21
I solved the `error: failed to exec scriptlet interpreter /bin/sh: Permission denied` issue by disabling SELinux (run `setenforce Permissive` as root outside the toolbox)

**Comment by debarshiray** [comment] 2019-07-22 14:36
Duplicate of #47

**Closed by debarshiray** 2019-07-22 14:36 UTC
