### ISSUE TITLE
Cant create toolbox image on Fedora 30 - Workstation

### ISSUE THREAD

**Issue by thawkins** [debarshiray/toolbox#174] opened 2019-05-24 07:54 UTC
I'm having problems getting toolbox to work on Fed30-Workstation

Note we are getting the same issues on Fed30-Silverblue

When I run the toolbox create i get the following.

```
[tim.hawkins@localhost toolbox-0.0.10]$ sudo setsebool virt_sandbox_use_fusefs on
[tim.hawkins@localhost toolbox-0.0.10]$ sudo rm -rf ~/.config/containers; sudo rm -rf ~/.local/share/containers
[tim.hawkins@localhost toolbox-0.0.10]$ ./toolbox -v create
toolbox: resolved absolute path for ./toolbox to /home/tim.hawkins/bin/toolbox-0.0.10/toolbox
toolbox: TOOLBOX_PATH is /home/tim.hawkins/bin/toolbox-0.0.10/toolbox
toolbox: checking if 'podman system migrate' exists
toolbox: migration not needed: 1.3.1 is unchanged
toolbox: Fedora generational core is f30
toolbox: base image is fedora-toolbox:30
toolbox: container is fedora-toolbox-30
toolbox: checking value /var/run/.heim_org.h5l.kcm-socket (Stream) of property Listen in sssd-kcm.socket
toolbox: parsing value /var/run/.heim_org.h5l.kcm-socket (Stream) of property Listen in sssd-kcm.socket
toolbox: checking if 'podman create' supports --dns=none and --no-hosts
toolbox: 'podman create' supports --dns=none and --no-hosts
toolbox: looking for image localhost/fedora-toolbox:30
WARN[0000] using rootless single mapping into the namespace. This might break some images. Check /etc/subuid and /etc/subgid for adding subids 
toolbox: looking for image registry.fedoraproject.org/f30/fedora-toolbox:30
WARN[0000] using rootless single mapping into the namespace. This might break some images. Check /etc/subuid and /etc/subgid for adding subids 
Image required to create toolbox container.
Download registry.fedoraproject.org/f30/fedora-toolbox:30 (500MB)? [y/N]: y
toolbox: pulling image registry.fedoraproject.org/f30/fedora-toolbox:30
WARN[0000] using rootless single mapping into the namespace. This might break some images. Check /etc/subuid and /etc/subgid for adding subids 
Trying to pull registry.fedoraproject.org/f30/fedora-toolbox:30...Getting image source signatures
Copying blob eb96ef222807 done
Copying blob 4c4fc0337a75 done
Copying config 42cdab313e done
Writing manifest to image destination
Storing signatures
ERRO[0057] Error pulling image ref //registry.fedoraproject.org/f30/fedora-toolbox:30: Error committing the finished image: error adding layer with blob "sha256:eb96ef22280741ab1ebfb5033fed1b54ad0ad7a3fe8c86acb5e779409d2ad136": Error processing tar file(exit status 1): there might not be enough IDs available in the namespace (requested 0:35 for /usr/libexec/utempter): lchown /usr/libexec/utempter: invalid argument 
Failed
Error: error pulling image "registry.fedoraproject.org/f30/fedora-toolbox:30": unable to pull registry.fedoraproject.org/f30/fedora-toolbox:30: unable to pull image: Error committing the finished image: error adding layer with blob "sha256:eb96ef22280741ab1ebfb5033fed1b54ad0ad7a3fe8c86acb5e779409d2ad136": Error processing tar file(exit status 1): there might not be enough IDs available in the namespace (requested 0:35 for /usr/libexec/utempter): lchown /usr/libexec/utempter: invalid argument
toolbox: failed to pull base image fedora-toolbox:30
[tim.hawkins@localhost toolbox-0.0.10]$ 


```

Im using 0.0.10, as the 0.0.9 in the fed30 updates rep does not get this far and cant set the newuidmap or newgidmap 

0.0.10 is better and gets further, but stops at this point.

**Comment by debarshiray** [comment] 2019-05-24 10:13
What does `/etc/subuid` and `/etc/subgid` look like? Does it have an entry for your user? I ask because of this error:
```
using rootless single mapping into the namespace. This might break some images. Check /etc/subuid and /etc/subgid for adding subids
```

This happens if your user was created with a relatively old version of `shadow-utils` and the OS was upgraded in-place after that. eg., this is how those files look on my system:
```
[rishi@kolache ~]$ cat /etc/subuid
rishi:100000:65536
[rishi@kolache ~]$ cat /etc/subgid
rishi:100000:65536
```

**Comment by thawkins** [comment] 2019-05-29 06:38
here is my files

```
[tim.hawkins@localhost tmp]$ echo $USER
tim.hawkins
[tim.hawkins@localhost tmp]$ cat /etc/subuid
tim.hawkins:100000:65536
[tim.hawkins@localhost tmp]$ cat /etc/subgid
tim.hawkins:100000:65536
[tim.hawkins@localhost tmp]$ 
```

**Comment by thawkins** [comment] 2019-05-29 06:41
Not sure if this would help
```

[tim.hawkins@localhost tmp]$ podman info
WARN[0000] using rootless single mapping into the namespace. This might break some images. Check /etc/subuid and /etc/subgid for adding subids 
host:
  BuildahVersion: 1.8.2
  Conmon:
    package: podman-1.3.1-1.git7210727.fc30.x86_64
    path: /usr/libexec/podman/conmon
    version: 'conmon version 1.12.0-dev, commit: c9a4c48d1bff85033b7fc9b62d25961dd5048689'
  Distribution:
    distribution: fedora
    version: "30"
  MemFree: 16282914816
  MemTotal: 33355350016
  OCIRuntime:
    package: containerd.io-1.2.5-3.1.fc29.x86_64
    path: /usr/sbin/runc
    version: |-
      runc version 1.0.0-rc6+dev
      commit: 2b18fe1d885ee5083ef9f0838fee39b62d653e30
      spec: 1.0.1-dev
  SwapFree: 16785600512
  SwapTotal: 16785600512
  arch: amd64
  cpus: 12
  hostname: localhost.localdomain
  kernel: 5.0.17-300.fc30.x86_64
  os: linux
  rootless: true
  uptime: 3h 25m 37.07s (Approximately 0.12 days)
registries:
  blocked: null
  insecure: null
  search:
  - docker.io
  - registry.fedoraproject.org
  - quay.io
  - registry.access.redhat.com
  - registry.centos.org
store:
  ConfigFile: /home/tim.hawkins/.config/containers/storage.conf
  ContainerStore:
    number: 0
  GraphDriverName: overlay
  GraphOptions:
  - overlay.mount_program=/usr/bin/fuse-overlayfs
  GraphRoot: /home/tim.hawkins/.local/share/containers/storage
  GraphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "false"
  ImageStore:
    number: 0
  RunRoot: /tmp/1000
  VolumePath: /home/tim.hawkins/.local/share/containers/storage/volumes

[tim.hawkins@localhost tmp]$ 

```

**Comment by thawkins** [comment] 2019-05-29 06:48
podman works

```
[tim.hawkins@localhost tmp]$ podman run hello-world
WARN[0000] using rootless single mapping into the namespace. This might break some images. Check /etc/subuid and /etc/subgid for adding subids 
Trying to pull docker.io/library/hello-world...Getting image source signatures
Copying blob 1b930d010525 done
Copying config fce289e99e done
Writing manifest to image destination
Storing signatures

Hello from Docker!
This message shows that your installation appears to be working correctly.

To generate this message, Docker took the following steps:
 1. The Docker client contacted the Docker daemon.
 2. The Docker daemon pulled the "hello-world" image from the Docker Hub.
    (amd64)
 3. The Docker daemon created a new container from that image which runs the
    executable that produces the output you are currently reading.
 4. The Docker daemon streamed that output to the Docker client, which sent it
    to your terminal.

To try something more ambitious, you can run an Ubuntu container with:
 $ docker run -it ubuntu bash

Share images, automate workflows, and more with a free Docker ID:
 https://hub.docker.com/

For more examples and ideas, visit:
 https://docs.docker.com/get-started/

[tim.hawkins@localhost tmp]$ 


```

**Comment by debarshiray** [comment] 2019-05-29 13:48
Interesting. Do things get better if you revert back to `podman-1.2.0`?

**Comment by thawkins** [comment] 2019-05-30 06:35
@debarshiray, i will try it tonight and report back.

**Comment by thawkins** [comment] 2019-05-31 03:44
Down graded to podman 1.2.0

still no joy

Note when downgrading from podman 1.3.x to 1.2.x you have to remove podman-manpages, as it appears they where split out into a separate package between 1.2.x and 1.3.x

```
[tim.hawkins@localhost ~]$ sudo dnf remove podman-manpages
Dependencies resolved.
======================================================================================================================================================================
 Package                                  Architecture                    Version                                             Repository                         Size
======================================================================================================================================================================
Removing:
 podman-manpages                          noarch                          2:1.3.1-1.git7210727.fc30                           @updates                          122 k

Transaction Summary
======================================================================================================================================================================
Remove  1 Package

Freed space: 122 k
Is this ok [y/N]: y
Running transaction check
Transaction check succeeded.
Running transaction test
Transaction test succeeded.
Running transaction
  Preparing        :                                                                                                                                              1/1 
  Erasing          : podman-manpages-2:1.3.1-1.git7210727.fc30.noarch                                                                                             1/1 
  Running scriptlet: podman-manpages-2:1.3.1-1.git7210727.fc30.noarch                                                                                             1/1 
  Verifying        : podman-manpages-2:1.3.1-1.git7210727.fc30.noarch                                                                                             1/1 

Removed:
  podman-manpages-2:1.3.1-1.git7210727.fc30.noarch                                                                                                                    

Complete!
[tim.hawkins@localhost ~]$ sudo dnf downgrade podman
Last metadata expiration check: 1:22:21 ago on Fri 31 May 2019 10:12:59 AM PST.
Dependencies resolved.
======================================================================================================================================================================
 Package                            Architecture                       Version                                               Repository                          Size
======================================================================================================================================================================
Downgrading:
 podman                             x86_64                             2:1.2.0-2.git3bd528e.fc30                             fedora                              11 M

Transaction Summary
======================================================================================================================================================================
Downgrade  1 Package

Total size: 11 M
Is this ok [y/N]: y
Downloading Packages:
[SKIPPED] podman-1.2.0-2.git3bd528e.fc30.x86_64.rpm: Already downloaded                                                                                              
Running transaction check
Transaction check succeeded.
Running transaction test
Transaction test succeeded.
Running transaction
  Preparing        :                                                                                                                                              1/1 
  Running scriptlet: podman-2:1.2.0-2.git3bd528e.fc30.x86_64                                                                                                      1/1 
  Downgrading      : podman-2:1.2.0-2.git3bd528e.fc30.x86_64                                                                                                      1/2 
  Cleanup          : podman-2:1.3.1-1.git7210727.fc30.x86_64                                                                                                      2/2 
  Running scriptlet: podman-2:1.3.1-1.git7210727.fc30.x86_64                                                                                                      2/2 
  Verifying        : podman-2:1.2.0-2.git3bd528e.fc30.x86_64                                                                                                      1/2 
  Verifying        : podman-2:1.3.1-1.git7210727.fc30.x86_64                                                                                                      2/2 

Downgraded:
  podman-2:1.2.0-2.git3bd528e.fc30.x86_64                                                                                                                             

Complete!
[tim.hawkins@localhost ~]$ podman run hello-world

Hello from Docker!
This message shows that your installation appears to be working correctly.

To generate this message, Docker took the following steps:
 1. The Docker client contacted the Docker daemon.
 2. The Docker daemon pulled the "hello-world" image from the Docker Hub.
    (amd64)
 3. The Docker daemon created a new container from that image which runs the
    executable that produces the output you are currently reading.
 4. The Docker daemon streamed that output to the Docker client, which sent it
    to your terminal.

To try something more ambitious, you can run an Ubuntu container with:
 $ docker run -it ubuntu bash

Share images, automate workflows, and more with a free Docker ID:
 https://hub.docker.com/

For more examples and ideas, visit:
 https://docs.docker.com/get-started/

[tim.hawkins@localhost ~]$ toolbox -v create
toolbox: resolved absolute path for /usr/bin/toolbox to /usr/bin/toolbox
toolbox: TOOLBOX_PATH is /usr/bin/toolbox
toolbox: checking if 'podman system migrate' exists
toolbox: migration not needed: 'podman system migrate' doesn't exist
toolbox: Fedora generational core is f30
toolbox: base image is fedora-toolbox:30
toolbox: container is fedora-toolbox-30
toolbox: checking value /var/run/.heim_org.h5l.kcm-socket (Stream) of property Listen in sssd-kcm.socket
toolbox: parsing value /var/run/.heim_org.h5l.kcm-socket (Stream) of property Listen in sssd-kcm.socket
toolbox: checking if 'podman create' supports --dns=none and --no-hosts
toolbox: 'podman create' supports --dns=none and --no-hosts
toolbox: looking for image localhost/fedora-toolbox:30
WARN[0000] using rootless single mapping into the namespace. This might break some images. Check /etc/subuid and /etc/subgid for adding subids 
toolbox: looking for image registry.fedoraproject.org/f30/fedora-toolbox:30
WARN[0000] using rootless single mapping into the namespace. This might break some images. Check /etc/subuid and /etc/subgid for adding subids 
Image required to create toolbox container.
Download registry.fedoraproject.org/f30/fedora-toolbox:30 (500MB)? [y/N]: y
toolbox: pulling image registry.fedoraproject.org/f30/fedora-toolbox:30
WARN[0000] using rootless single mapping into the namespace. This might break some images. Check /etc/subuid and /etc/subgid for adding subids 
Trying to pull docker://registry.fedoraproject.org/f30/fedora-toolbox:30...Getting image source signatures
Copying blob eb96ef222807 done
Copying blob 4c4fc0337a75 done
Copying config 42cdab313e done
Writing manifest to image destination
Storing signatures
ERRO[0110] Error pulling image ref //registry.fedoraproject.org/f30/fedora-toolbox:30: Error committing the finished image: error adding layer with blob "sha256:eb96ef22280741ab1ebfb5033fed1b54ad0ad7a3fe8c86acb5e779409d2ad136": Error processing tar file(exit status 1): there might not be enough IDs available in the namespace (requested 0:35 for /usr/libexec/utempter): lchown /usr/libexec/utempter: invalid argument 
Failed
(0x555607d9a5c0,0xc00081b720)
Error: error pulling image "registry.fedoraproject.org/f30/fedora-toolbox:30": Invalid image name "registry.fedoraproject.org/f30/fedora-toolbox:30", unknown transport "registry.fedoraproject.org/f30/fedora-toolbox"
toolbox: failed to pull base image fedora-toolbox:30
[tim.hawkins@localhost ~]$
```

**Comment by thawkins** [comment] 2019-05-31 04:08
I seem to have fixed it, but im not sure why. 

```
[tim.hawkins@localhost ~]$ sudo dnf install shadow-utils
Last metadata expiration check: 1:50:41 ago on Fri 31 May 2019 10:12:59 AM PST.
Package shadow-utils-2:4.6-8.fc30.x86_64 is already installed.
Dependencies resolved.
Nothing to do.
Complete!
[tim.hawkins@localhost ~]$ sudo dnf reinstall shadow-utils
Last metadata expiration check: 1:50:48 ago on Fri 31 May 2019 10:12:59 AM PST.
Dependencies resolved.
======================================================================================================================================================================
 Package                                   Architecture                        Version                                      Repository                           Size
======================================================================================================================================================================
Reinstalling:
 shadow-utils                              x86_64                              2:4.6-8.fc30                                 fedora                              1.1 M

Transaction Summary
======================================================================================================================================================================

Total download size: 1.1 M
Installed size: 5.0 M
Is this ok [y/N]: y
Downloading Packages:
shadow-utils-4.6-8.fc30.x86_64.rpm                                                                                                    468 kB/s | 1.1 MB     00:02    
----------------------------------------------------------------------------------------------------------------------------------------------------------------------
Total                                                                                                                                 371 kB/s | 1.1 MB     00:03     
Running transaction check
Transaction check succeeded.
Running transaction test
Transaction test succeeded.
Running transaction
  Preparing        :                                                                                                                                              1/1 
  Reinstalling     : shadow-utils-2:4.6-8.fc30.x86_64                                                                                                             1/2 
  Cleanup          : shadow-utils-2:4.6-8.fc30.x86_64                                                                                                             2/2 
  Running scriptlet: shadow-utils-2:4.6-8.fc30.x86_64                                                                                                             2/2 
  Verifying        : shadow-utils-2:4.6-8.fc30.x86_64                                                                                                             1/2 
  Verifying        : shadow-utils-2:4.6-8.fc30.x86_64                                                                                                             2/2 

Reinstalled:
  shadow-utils-2:4.6-8.fc30.x86_64                                                                                                                                    

Complete!
[tim.hawkins@localhost ~]$ podman run fedora cat /proc/self/uid_map
Trying to pull docker.io/library/fedora...Getting image source signatures
Copying blob 01eb078129a0 done
Copying config d09302f77c done
Writing manifest to image destination
Storing signatures
         0       1000          1
         1      10000      65536
[tim.hawkins@localhost ~]$ toolbox -v create
toolbox: resolved absolute path for /usr/bin/toolbox to /usr/bin/toolbox
toolbox: TOOLBOX_PATH is /usr/bin/toolbox
toolbox: checking if 'podman system migrate' exists
toolbox: migration not needed: 'podman system migrate' doesn't exist
toolbox: Fedora generational core is f30
toolbox: base image is fedora-toolbox:30
toolbox: container is fedora-toolbox-30
toolbox: checking value /var/run/.heim_org.h5l.kcm-socket (Stream) of property Listen in sssd-kcm.socket
toolbox: parsing value /var/run/.heim_org.h5l.kcm-socket (Stream) of property Listen in sssd-kcm.socket
toolbox: checking if 'podman create' supports --dns=none and --no-hosts
toolbox: 'podman create' supports --dns=none and --no-hosts
toolbox: looking for image localhost/fedora-toolbox:30
toolbox: looking for image registry.fedoraproject.org/f30/fedora-toolbox:30
Image required to create toolbox container.
Download registry.fedoraproject.org/f30/fedora-toolbox:30 (500MB)? [y/N]: y
toolbox: pulling image registry.fedoraproject.org/f30/fedora-toolbox:30
Trying to pull docker://registry.fedoraproject.org/f30/fedora-toolbox:30...y
Getting image source signatures
Copying blob 4c4fc0337a75 done
Copying blob eb96ef222807 done
Copying config 42cdab313e done
Writing manifest to image destination
Storing signatures
toolbox: base image fedora-toolbox:30 resolved to registry.fedoraproject.org/f30/fedora-toolbox:30
toolbox: checking if container fedora-toolbox-30 already exists
toolbox: trying to create container fedora-toolbox-30
Created container: fedora-toolbox-30
Enter with: toolbox enter
[tim.hawkins@localhost ~]$]
```

**Comment by thawkins** [comment] 2019-05-31 04:17
Just reinstalled podman 1.3.1 and it still works with toolbox 0.0.10 from the  fedora-updates repository.

This is a big load off my mind as it was the last blocker to us rolling out Silverblue to our 50+ dev software development department.

**Comment by thawkins** [comment] 2019-06-01 04:23
Spoke too soon, i'm now suffering from #182 , but that is a different problem.

**Comment by juhp** [comment] 2019-06-01 13:06
I can reproduce this too on a clean up-to-date Fedora 30 Workstation install with
latest snapshot podman-1.3.2-1559353158.git2068919e.fc30 (copr) and toolbox (0886fb4).

**Comment by juhp** [comment] 2019-07-03 09:48
I think this could be closed now?

**Comment by thawkins** [comment] 2019-07-04 04:42
have we resolved why it takes two tries to make entering toolbox work?

**Comment by juhp** [comment] 2019-07-04 06:46
@thawkins do you mean #212?

**Comment by meeuw** [comment] 2019-07-14 08:21
After running
```
podman system prune
podman system renumber
podman system migrate
```
The above error was fixed for me.

**Comment by debarshiray** [comment] 2019-09-17 16:18
Let's close this one. It has bounced from one issue to another, and at this point it will be better to use a new issue for remaining problems.

Thanks for getting in touch and persevering through all the problems!

**Closed by debarshiray** 2019-09-17 16:18 UTC
